### ISSUE TITLE
Remove "Show Rows with the Following Values" div

### ISSUE THREAD

**Issue by jhabr** [freddyaboulton/gradio-leaderboard#12]
When using this simple example from the demo:

```python
import pandas as pd
import gradio as gr
from gradio_leaderboard import Leaderboard, SearchColumns

with gr.Blocks() as demo:
    Leaderboard(
        value=pd.DataFrame({"name": ["Freddy", "Maria", "Mark"], "country": ["USA", "Mexico", "USA"]}),
        search_columns=SearchColumns(
            primary_column="name",
            secondary_columns=["country"],
            placeholder="Search by name or country. To search by country, type 'country:<query>'",
            label="Search"
        ),
    )

demo.launch()

```
the rendered UI looks like this:

<img width="1498" alt="Screenshot 2024-06-21 at 19 01 35" src="https://github.com/freddyaboulton/gradio-leaderboard/assets/25850/73d7dc22-866f-49e9-94d7-647530e8148b">

Is there a way to remove the `div` containing the text `Show Rows with the Following Values`?

I assume it has to do with the `filterColumns` checkboxes?

https://github.com/freddyaboulton/gradio-leaderboard/blob/8bf27c0fd4b4792e83531c4cebf6deba043d3b6b/frontend/Index.svelte#L316

I'm using `gradio-leaderboard==0.0.9`.

**Comment by freddyaboulton** [comment]
Would you like to open a PR for this? Just need to set `show_label` to false if there are no filter columns. Or only display the checkbox if there are filter columns.
